### ISSUE TITLE
Use of `any` types makes library almost impossible to use

### ISSUE THREAD

**Issue by garth** [Alfresco/alfresco-js-api#1076]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ ] Bug  
- [ ] Support request
- [x] DX improvement
```
**Current behavior:**

```
    nodesApi.listNodeChildren('-root-', untypedOptions)
```

options are of type `any`, there is no obvious way to discover or validate options.
   

**Expected behavior:**

```
    const nodes = await nodesApi.listNodeChildren('-root-', {
      relativePath: '/some/folder', // currently undocumented magic key that lets you list files in a folder
    })
```

**Steps to reproduce the issue:**

**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
yep I agree many of the methods are autogenerated from the API explorer definition file we should first enhance this https://github.com/Alfresco/rest-api-explorer
