### ISSUE TITLE
Running tsc after importing @alfresco/js-api throws 900 errors

### ISSUE THREAD

**Issue by garth** [Alfresco/alfresco-js-api#1082]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**

Import the alfresco api into a typescript file

```ts
import { AlfrescoApi } from '@alfresco/js-api'
```

run `tsc --noEmit` to validate. Currently there are 900 errors reported in various files under `node_modules/@alfresco/js-api`

I would guess the errors could be removed if the lib was packaged differently. The compiler is picking up the ts files insted of the js/d.ts files because they are in the same src folder. Maybe removing the ts files from the npm publish would fix?

**Expected behavior:**

no errors

**Steps to reproduce the issue:**

**Node version (for build issues):**  

Node 15.14.0
TS 4.2.4

tsconfig
```json
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "downlevelIteration": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "preserveConstEnums": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "target": "es5"
  }
}

```

**New feature request:**

**Comment by DenysVuika** [comment]
Normally, you should also have the `exclude` provided:

```
"exclude": ["node_modules"],
```

Have you tried this one?

**Comment by garth** [comment]
I ommited my inclusion/exclusion rules.

Of course another fix would be to actually address the 900 type errors, most of which are due to not checking for undefined.

Typescript now support `?.` which would fix many of the errors.

**Comment by DenysVuika** [comment]
Just switch off the `strict` mode for now. There's another issue open of the `strict` mode support

**Comment by garth** [comment]
It looks like it would be possible to fix by output the tsc build to a separate folder (or adding a .npmignore rule). I've tested locally by separating the files and that seems to do the trick. Would you accept a PR?

**Comment by DenysVuika** [comment]
There was a PR merged yesterday, will that help? https://github.com/Alfresco/alfresco-js-api/pull/1081

**Comment by garth** [comment]
The PR description seems to describe the same issue. I'm trying test the PR locally, but one of the project dependences (iltorb) won't build.

**Comment by garth** [comment]
Ok I have manage to get it working, seems that npm install/build are only compatible with node 12. (Maybe consider `volta pin node@12`)

I can confirm that #1081 does fix the library in typescript projects.

**Comment by garth** [comment]
Ok I have manage to get it working, seems that npm install/build are only compatible with node 12. (Maybe consider `volta pin node@12`)

I can confirm that #1081 does fix the library in typescript projects.
