### ISSUE TITLE
Wrong type definition for nodesApi.getNodeContent

### ISSUE THREAD

**Issue by garth** [Alfresco/alfresco-js-api#1139]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x ] Bug  
- [ ] Support request
```
**Current behavior:**

Marked as returning a `Promise<Blob>` but actually returns a `Promise<Buffer>`

**Expected behavior:**

Type declaration should match implementation.

**Steps to reproduce the issue:**

**Node version (for build issues):**  

**New feature request:**

**Comment by DenysVuika** [comment]
This probably was related to how you were running the api - Browser or Node.js, according to the latest docs:
> Blob class is a global reference for require('node: buffer').Blob

And Node 18 (current target) should already be supporting Blob alongside the browser

- https://developer.mozilla.org/en-US/docs/Web/API/Blob
- https://nodejs.org/api/buffer.html#class-blob
