### ISSUE TITLE
Can't upload PDF

### ISSUE THREAD

**Issue by sredrouthu** [Alfresco/alfresco-js-api#135]
**Type of issue:** PDF Upload

**Current behavior:**
I'm trying to upload a PDF, but getting an error as follows.
"Weird single-character line '+' found (in topic random) at stream() line 1082"
uploadFile(fileDefinition, relativePath, nodeId, nodeBody, opts)

**Expected behavior:**
PDF should be uploaded successfully. 

**Steps to reproduce the issue:**
Please try uploading a PDF file.

**Comment by eromano** [comment]
Hi @sredrouthu ,
The pdf uploading sholud work fine.
Below you can find an example app made with angular 2 that use the alfresco-js-api behind and I just test it with a PDF and it works fine.
https://github.com/Alfresco/alfresco-ng2-components/tree/master/ng2-components/ng2-alfresco-upload
If you can provide more information maybe I can help you. You could provide also a snippet or your code maybe .

**Comment by sredrouthu** [comment]
Hi @eromano,

PDF Upload Working fine. Thank you.
