### ISSUE TITLE
Create config option to change API root rather than using hardcoded "/api/"

### ISSUE THREAD

**Issue by davidcognite** [Alfresco/alfresco-js-api#141]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
```
**Current behavior:**

Share has a built-in proxy to the remote API. The URL for that is, e.g.:
http://localhost:8181/share/proxy/alfresco-api/-default-/public/alfresco/versions/1/nodes/43485b48-2ca7-4077-a00c-9bfe810f9fa1

This URL is not possible to achieve with the current configuration options, as there is a hardcoded "api/" prefixed before "-default-" in the URL. (e.g.: https://github.com/Alfresco/alfresco-js-api/blob/2f6d3f9b6b790ad6b7dbb497ff71a2eb710e34ea/src/ecmClient.js#L28 )

The following config can be used within Aikau to load the JS API:
```javascript
            // Remove leading slash from URL Context as JS API adds one between hostEcm and contextRoot
            var shareContextRoot = AlfConstants.URL_CONTEXT.slice(1);
            this.alfrescoJsApi = new AlfrescoApi({
               provider: "ECM",
               hostEcm: window.location.protocol + "//" + window.location.host,
               // FIXME: JS API code adds /api between this and "-default-" in the API URL.
               contextRoot: shareContextRoot + "proxy/alfresco-api"
            });
```
**Expected behavior:**

It would be useful to add an optional apiRoot (or similar) config param that defaults to "api" but in the case of Share it could be configured to "alfresco-api".

This would be useful because being able to configure the JS API to use Share's built in proxy allows Surf to handle authentication (it uses the user's existing log in session) and bypasses any CORS issues.

**Steps to reproduce the issue:**

See Aikau mixin here: https://github.com/Alfresco/Aikau/commit/d66b21659f684f19791c5d885f40bd6f06e24d1b

and example use of this mixin here:
https://gitlab.alfresco.com/records-management/records-management/commit/89501bba4b3c7f57b67828ba094242fd71cef3e5

**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
@davidcognite Can you point me how to change this api root from the community edition? thanks. I would like to test it against it before to made this change

**Comment by eromano** [comment]
@davidcognite in order to cahnge the basePath of the api you can do in this way

After the init of the api:

```ts 
this.alfrescoJsApi = new AlfrescoApi({YOUR_CONFIG}); 
``` 
you can modify the basePath of the Alfresco ECM client.

```ts 
 this.alfrescoJsApi.ecmClient.basePath = ‘YOUR_BASE_PATH’
``` 
usually this bas path is :

```ts 
this.basePath = host + '/' + this.contextRoot + '/api/-default-/public/alfresco/versions/1';
``` 

I hope that can help you
