### ISSUE TITLE
Publish alfresco-js-api to Nexus use from Maven

### ISSUE THREAD

**Issue by davidcognite** [Alfresco/alfresco-js-api#142]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
```
**New feature request:**

It'll be far easier for us to use the JS API in RM apps, as well as ones based on the SDK if the build published the artefacts to nexus in addition to npm so they can be included as regular maven dependencies. (e.g. as Aikau does with Dojo).

**Comment by eromano** [comment]
@davidcognite I think this is a question to @enzor

**Comment by eromano** [comment]
@davidcognite  for use the js-api from maven you should be able to use:
```
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>alfresco-js-api</artifactId>
			<version>1.1.0</version>
		</dependency>
```
