### ISSUE TITLE
Build fails with test errors

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-js-api#145]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**
`npm run build` command fails with test errors:

```
 1) Auth ECM Provider config With Authentication login should return an error if wrong credential are used 400 userId and/or password are/is not provided:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  
  2) Ecm Auth test With Authentication login should return an error if wrong credential are used 400 userId and/or password are/is not provided:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Expected behavior:**
script executes without errors

**Steps to reproduce the issue:**

**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
@DenisVuyka I don't see this error on master and in develop branch

**Comment by DenisVuyka** [comment]
Closing as cannot reproduce after deleting `node_modules` folder and reinstalling dependencies.

**Comment by DenisVuyka** [comment]
This issue happens after several rebuilds and/or npm-linking this library with `demo-shell`. It seems some unit tests don't use mocks and try calling real endpoints, so end up with timeout.
