### ISSUE TITLE
runtime

### ISSUE THREAD

**Issue by maccarilab** [Alfresco/alfresco-js-api#1491]
Hi, I'm new for ALFRESCO. 
What can I do to test the solution?
I run npm run build and npm run test.
I have this web site http://localhost:9876/?id=70331149 with no menu, no login.
Before reverse engineering by reading code, I'd like to have some ideas.
Thanks in advance.
Sergio

**Comment by DenysVuika** [comment]
If that relates to JS-API project, please provide more context and steps to reproduce the issue.
