### ISSUE TITLE
Error on authentication with bpm

### ISSUE THREAD

**Issue by cdschwarz** [Alfresco/alfresco-js-api#166]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x ] Bug  
- [ ] Support request
```
**Current behavior:**
(from nodejs version 6.9.1 with Activiti Community edition, rest api) Using the sample authentication with BPM:
this.alfrescoJsApi = new AlfrescoApi({ provider:'BPM' });

this.alfrescoJsApi.login('admin', 'admin').then(function (data) {
    console.log('API called successfully Login in Activiti BPM performed ');
}, function (error) {
    console.error(error);
});

Results in the following error:
TypeError: Right-hand side of 'instanceof' is not an object
    at BpmAuth.exports.isFileParam (/Users/eromano/Projects/dev-platform-js-api/dist/alfresco-js-api.js:42056:98)
    at BpmAuth.exports.normalizeParams (/Users/eromano/Projects/dev-platform-js-api/dist/alfresco-js-api.js:42093:18)
    at BpmAuth.callApi (/Users/eromano/Projects/dev-platform-js-api/dist/alfresco-js-api.js:58529:51)
    at /Users/eromano/Projects/dev-platform-js-api/dist/alfresco-js-api.js:59080:20
    at BpmAuth.login (/Users/eromano/Projects/dev-platform-js-api/dist/alfresco-js-api.js:59079:24)

**Expected behavior:**
       successful authentication
**Steps to reproduce the issue:**
(above)

**Node version (for build issues):**  

6.9.1
**New feature request:**
Request support for using this api for node.js from community edition of Activiti rest api

Thanks!

**Comment by eromano** [comment]
Hi @cdschwarz ,
can you try to modify the package.json of alfresco-js-api and cahnge ``` "main": "dist/alfresco-js-api.js" ``` with ``` "main": "main.js" ```?

**Comment by DenisVuyka** [comment]
@eromano It seems the Community edition is used. We don't support it for the moment.

**Comment by cdschwarz** [comment]
changing "main": "dist/alfresco-js-api.js" with "main": "main.js" did seem to resolve that error.  
The error now says "cannot POST to /activiti-app/app/authentication"  , I assume this is due to use the community edition.  

Should I submit a separate request to support the community edition?  Thanks!

**Comment by eromano** [comment]
@DenisVuyka I know that but the stack trace is reproducible also on the others version of activiti

**Comment by eromano** [comment]
@cdschwarz yep the authentication issue is a separate issue
