### ISSUE TITLE
activiti community edition request

### ISSUE THREAD

**Issue by cdschwarz** [Alfresco/alfresco-js-api#170]
**Type of issue:**  (check with "[x]")
```
- [x ] New feature request
- [ ] Bug  
- [ ] Support request
```
**Current behavior:**
api is not supported for community version of activiti

**Expected behavior:**

**Steps to reproduce the issue:**

**Node version (for build issues):**  
6.9.1

**New feature request:**
Request support for community edition of activiti.  Realize this may be a high level of effort to integrate, but we do not need the enterprise edition and it would be great to utilize this api for the community edition.
thanks for your consideration

**Comment by fcorti** [comment]
ADF supports the Activiti Community edition since version 3.3.
Will close this issue then.
Cheers.
