### ISSUE TITLE
Property 'webScript' does not exist on type 'AlfrescoApi'

### ISSUE THREAD

**Issue by suzhen-github** [Alfresco/alfresco-js-api#1751]
I used ''this.apiService.getInstance().webScripti.executeWebScript''  to call custom webscript api from ADF4.2,
but After I upgraded ADF4.2 to ADF6, the following error occurred.

"Property 'webScript' does not exist on type 'AlfrescoApi'"

I have tried the following method, but it doesn't work.

const scriptPath = '/tai/gettaicategorylist';
this.apiService.getInstance().contentClient.callApi(
        scriptPath, 'POST', scriptArgs, scriptArgs, scriptArgs, {}, postBody, ['application/json'], ['application/json'],{'String': 'String'},contextRoot,'application/json')

Please, we need help. thanks a lot.

**Comment by DenysVuika** [comment]
The JS-API project has been merged with the ADF repository, so better referring there. Also, please check the unit tests to see how the Api classes are worked in this or that case. For example: https://github.com/Alfresco/alfresco-ng2-components/blob/a54b2bd450c2cbd2e85578fac92854d3848410ae/lib/js-api/test/content-services/webScriptApi.spec.ts#L45
