### ISSUE TITLE
loginTicket(ticket) 400 response 

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-js-api#209]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x ] Bug  
- [ ] Support request
```
**Current behavior:**

```javascript
                    this.alfrescoJsApi.loginTicket(ticket).then((data) => {
                        console.log(ticket);
                        expect(data).to.be.equal(ticket);
                        done();
                    },(err)=> {
                        console.log(err);
                    });
```
"errorKey":"Ticket base authentication required.","statusCode":400,"briefSummary":"03030007 Ticket base authentication required."

**Expected behavior:**

from the response seems that the in the  loginTicket  is not provided  the ticket by the Authorization header, the ticket should be present in the header.

**Steps to reproduce the issue:**

**Node version (for build issues):**  

**New feature request:**

**Comment by martinehe** [comment]
checked out the new version and can confirm - the issue is resolved. Thanks...
