### ISSUE TITLE
isLoggedIn method of EcmAuth client is returning "true" when ticket expires

### ISSUE THREAD

**Issue by chris-equis** [Alfresco/alfresco-js-api#210]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**

calling `isLoggedIn()` returns `true` if the ticket is expired

**Expected behavior:**

calling `isLoggedIn()` should return false if the ticket is expired

**Steps to reproduce the issue:**

1. Use [EcmAuth](https://github.com/Alfresco/alfresco-js-api/blob/master/src/ecmAuth.js) instance to login with valid credentials
2. Check that the `ticket-ECM` key was registered in LocalStorage and it has stored the ticket
3. Wait until the ticket expires or modify (not delete) the ticket directly in LocalStorage
4. `console.log(instance.isLoggedIn())` returns `true` because [it just checks that there is a ticket](https://github.com/Alfresco/alfresco-js-api/blob/master/src/ecmAuth.js#L155) but not its validity

**Comment by eromano** [comment]
In the alfresco-js-api is already present validateTicket() method that checks the ticket against the server and returns a promise.

Change now the isLoggedIn in this way could have two side effects:

- too many calls against the server 
- breaking change with the firm of the actual isLoggedIn 

We could think a way to check the token if is still valid and invalidate the localstorage after some events as 401
