### ISSUE TITLE
Revert changes added with #65 unless activiti provides new enterprise endpoint

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-js-api#217]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x ] Bug  
- [ ] Support request
```
**Current behavior:**
On completed  task the call for task/variables fail cause it works only for running tasks

**Expected behavior:**
task variables should be retrieved even on completed forms.

**Steps to reproduce the issue:**

**Node version (for build issues):**  

**New feature request:**

**Comment by tdonovancsra** [comment]
please fix +1

**Comment by eromano** [comment]
@tdonovancsra I reopened the https://github.com/Alfresco/alfresco-js-api/issues/199. This api will be probably released in the version 16.1 or 1.6.2 of activiti. we will wait before the release of this fix before to reintroduce it

**Comment by tdonovancsra** [comment]
so does that mean the call goes back to the REST api?

**Comment by eromano** [comment]
sorry @tdonovancsra wich is the problem that you are experiencing as far as I know this modify should not affect any functionality is change a change of the api between the public and the private

**Comment by tdonovancsra** [comment]
on completed cases I am receiving 404 not found when it makes the call to get the variables

/api/enterprise/tasks/{}/variables

**Comment by tdonovancsra** [comment]
is there a workaround until 1.6.2?

**Comment by eromano** [comment]
@tdonovancsra this PR is about to change this endpoint that is not implemented yet in the public side with the private that is working: 

'/app/rest/task-forms/{taskId}/variables'

**Comment by tdonovancsra** [comment]
I'm going to have to override that method we can't wait that long.  If you switch it back it messes up the authentication scheme.   You should consider a different solution

**Comment by eromano** [comment]
@tdonovancsra sorry I don't get your point maybe I don't know enough about your scenario.
The alfresco.js-api 1.2 was already working like that using '/app/rest/task-forms/{taskId}/variables' and there are no problems about auth as far as I know.

**Comment by tdonovancsra** [comment]
yeah I voted for #199 because of this issue.  that call was not working for us.  We are using basic authentication to get to the backend and the /rest/ endpoint for the angular 1 app uses cookies.   That call fails for our scenario.
