### ISSUE TITLE
Consider shrink wrapping or fixing dependency versions for releases.

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-js-api#224]
Package.json includes ^1.x.y fuzzy versions. This is bad! ;) Also SDK has a surprising number of dependencies. If we shrink-wrap or even deliver a consolidated dependency in releases that would be excellent.

**Comment by eromano** [comment]
HI @binduwavell  in the next pacakge the dependency are only two:

```json
    "superagent": "3.4.1",
    "event-emitter": "0.3.4"
```

the other not fixed are devDepency we can deal with those not fixed. The devDepency are installed only if you need to build the alfresco-js-api.

**Comment by binduwavell** [comment]
Also with npm 5, it looks like versions will be locked down better as well. I have not investigated this too much yet, but if you check in the lock file, I think it will behave similar to shrinkwrap.

**Comment by DenisVuyka** [comment]
For 1.6 we have already switched to npm 5 and node 8, the lock files are now part of the repo and will be available once 1.6 is out.
