### ISSUE TITLE
External Authentication Support (X-Alfresco-Remote-User)

### ISSUE THREAD

**Issue by bricka** [Alfresco/alfresco-js-api#229]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
```

**New feature request:**

My team is interested in using Alfresco's "External Authentication" feature so that we can do some custom authentication work.  The feature is described here:
http://docs.alfresco.com/5.2/concepts/auth-external-props.html

In order to use this feature, we need to be able to set to set a specific header value whenever we make a request to Alfresco. The default header is `X-Alfresco-Remote-User`, but this is configurable within Alfresco.

Is this supported by `alfresco-js-api` today?  Or what can we do in order to support this?

Thank you very much!

**Comment by eromano** [comment]
Hi @bricka ,

At the moment this header is not supported,
We accept by the way external contribution and maybe if you give a look inside this script:

https://github.com/Alfresco/alfresco-js-api/blob/master/src/alfrescoApiClient.js

You can find a way to change it and set it as we do for the other headers.
