### ISSUE TITLE
Missing black slash in  var rsApos = "['\u2019]",

### ISSUE THREAD

**Issue by sunjianxy301** [Alfresco/alfresco-js-api#240]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ x] Bug  
- [ ] Support request
```
**Current behavior:**

Chrome cannot the index.html and complain "Uncaught Syntax Error..." raised from
line 21346 (version 1.4.0):
	  /** Used to match apostrophes. */
	  var reApos = RegExp(rsApos, 'g');
the production build when I deployed on nginx.

Line 21315
	  var rsApos = "['\u2019]",

**Expected behavior:**

Line 21315 should be 
	  var rsApos = "['\\u2019]",
Missing a '\'.

**Steps to reproduce the issue:**

With the project generated by yo generator, create the production build by "npm run build".
Then deploy it on the nginx. Then use the browser.

**Node version (for build issues):**  

Node version is not relevant here. I simply deploy it as the static contents on nginx.

**New feature request:**

**Comment by eromano** [comment]
Not sure about this bug. Doesn't sound something about alfresco-js-api

**Comment by DenisVuyka** [comment]
This code can be found in the `webpack-bundle-test.js`. Not sure why it is being loaded into the browser though.

<img width="883" alt="screenshot 2017-06-23 07 32 19" src="https://user-images.githubusercontent.com/503991/27469196-1f20f4ae-57e6-11e7-876b-104cb2f4b4fc.png">
