### ISSUE TITLE
ChangesAPI doesn't refer to any real API and duplicates other APIs

### ISSUE THREAD

**Issue by jmpascal** [Alfresco/alfresco-js-api#26]
Aloah,

As defined by documentation [here](https://github.com/Alfresco/alfresco-js-api/tree/master/src/alfresco-core-rest-api) we have **AlfrescoCoreRestApi.ChangesApi** class.

This class is useless and doesn't match any real Apis behind the scene. Furthermore same methods for this class are already integrated by other classes like NodesApi, SitesApi etc...
ChangesApi just reflect "new api changes" defined in swagger definition and integrated by the server for a specific version. It shouldn't be reflected by the JS API as it's more documentation information than a real API.

My recommendation is to ignore the code generation for this specific definition (ChangesApi) as

- it might change depending on Rest API version from the server so it might be difficult to support
- it works more like a shortcut than real stable API definition
- it's already integrated by other classes

Hope it helps.

**Comment by eromano** [comment]
Thanks  @jmpascal  I'll remove this discrepancy in the next release

**Comment by jmpascal** [comment]
Hi,

I might mis-explained the current issue in my previous comment but it would be better to remove completely the notion of  **ChangesApi **  class from everywhere inside the project.

After a simple research https://github.com/Alfresco/alfresco-js-api/search?utf8=%E2%9C%93&q=ChangesApi it couldbe  helpful to remove/refactor all those files 

- Deleting src/alfresco-core-rest-api/docs/ChangesApi.md 
- Deleting src/alfresco-core-rest-api/src/api/ChangesApi.js 
- Edit src/alfresco-core-rest-api/src/index.js 

Hope it helps.
