### ISSUE TITLE
Diffirence between BPM API calling endpoint and Activiti API docs

### ISSUE THREAD

**Issue by long241191** [Alfresco/alfresco-js-api#296]
Hi all.

I have an Activiti BPM server, and when I use publish API as Activiti User guide, it's work.
https://www.activiti.org/userguide/index.html#_rest_api
APIs schema allway start with http://host/actviti-rest/

But when I using this lib, I see APIs schema is difference, and I can't use this lib to connect with my Activiti BPM Server.

Example: API url to list all process definitions:
- With activiti docs: GET repository/process-definitions
- With this library: GET /app/rest/reporting/process-definitions

I'm using Activiti 5.18.0 (docker image https://hub.docker.com/r/cwoodcock/activiti/)

Please let's me know.
Many thanks.

**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ ] Bug  
- [x ] Support request
```
**Current behavior:**

**Expected behavior:**

**Steps to reproduce the issue:**

**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
The current status of this API support only the enterprise edition sorry.
