### ISSUE TITLE
Need to support SSO

### ISSUE THREAD

**Issue by ajmas** [Alfresco/alfresco-js-api#323]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
```
**Current behavior:**

**Expected behavior:**

Since the server in our environment uses external SSO we should be able to connect without any extra tokens. 

A check for isLoggedIn() should return true, but it never hits the remote server to check it already has access. 

**Steps to reproduce the issue:**

call alfrecoApi.isLoggedIn() returns false. 

Trying to log in without user or password does not appear to be supported by login()

No documentation illustrating this use case. 

**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
@ajmas which SSO are you using? are you targeting the CS or the PS?
We have the documentation on the only SSO at the moment supported OAUTH2 https://github.com/Alfresco/alfresco-js-api#login-with-oauth2-alfresco-authorization-server

**Comment by ajmas** [comment]
We are using SiteMinder. All our Tomcat servers are sitting behind Apache instances which manage the auth based on Kerberos tokens and simply pass on a header with the authenticated user. Alfresco is configured to use external auth.

**Comment by ajmas** [comment]
Oh and targeting content server

**Comment by eromano** [comment]
did you try to perform any action without execute the login? in kerberos it should works

**Comment by ajmas** [comment]
Without executing the login it works, though how would you recommend checking whether the user is already authenticated? Just need to have a portable way of checking, such that we present authentication options only when we aren't remotely authenticated?

**Comment by eromano** [comment]
I guess if a call reply 401  you are no authenticated and you should perform it

**Comment by ajmas** [comment]
The best solution I have found is calling is using the following code:

```
function isLoggedIn()
   return alfrescoApi.core.peopleApi.getPerson('-me-')
      .then(entry => {
         return false;
      })
     .catch(error => {
         // TODO do proper error handling
        return false;
     });
}
```

Based on this I am wondering whether the isLoggedIn() call should support some of this logic, so that it works with both SSO and non-SSO environments?

**Comment by eromano** [comment]
Withcredential is now supported thanks to your contribution too
