### ISSUE TITLE
It is not possible to upload a content with node.js

### ISSUE THREAD

**Issue by DenysVuika** [Alfresco/alfresco-js-api#343]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**
None of the examples provide a working solution for uploading with node.js. 
All APIs are browser-oriented and require the HTML5 FileApi objects that do not exist in node.js. 

**Expected behavior:**
It should be possible to upload content from node.js. 
Examples should provide a working code that devs can paste and run.

**Steps to reproduce the issue:**

**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
There is an example in the integration folder
