### ISSUE TITLE
api is missing on the JS-API level : 'api/enterprise/process-instances/{processInstanceId}/historic-variables'

### ISSUE THREAD

**Issue by ocevandaele** [Alfresco/alfresco-js-api#348]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ X] Bug  
- [ ] Support request
```
Hello,

What is the method with the API 'alfresco-js-api' to retrieve the query:
_'/enterprise/process-instances/{processInstanceId}/historic-variables'_

I look in all the read me at :
_https://github.com/Alfresco/alfresco-js-api/tree/master/src/alfresco-activiti-rest-api/docs_

I think this api is missing on the JS-API level ..?

**Comment by eromano** [comment]
Have you got a look at this pice of documentation: https://github.com/Alfresco/alfresco-js-api/blob/develop/src/api/activiti-rest-api/docs/ProcessinstancesApi.md#getHistoricProcessInstanceVariables

**Comment by fcorti** [comment]
Please check the link below:

https://github.com/Alfresco/alfresco-js-api/blob/a4b4bc4f8cf1346070448771479c894ca61214ca/src/api/activiti-rest-api/api/processInstances.api.ts#L241
