### ISSUE TITLE
Person is missing Capabilities (typings)

### ISSUE THREAD

**Issue by DenysVuika** [Alfresco/alfresco-js-api#349]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**
The Person type is missing Capabilities block

<img width="222" alt="screen shot 2018-07-07 at 10 49 40" src="https://user-images.githubusercontent.com/503991/42409542-95d506fe-81d3-11e8-84cd-9c6eaf127e77.png">

**Expected behavior:**
The typings should provide Capabilities properties

**Steps to reproduce the issue:**

**Node version (for build issues):**  

**New feature request:**

**Comment by fcorti** [comment]
Fixed 4 months ago.
