### ISSUE TITLE
Support withCredentials for SSO based environments

### ISSUE THREAD

**Issue by ajmas** [Alfresco/alfresco-js-api#357]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
```
**Current behavior:**

For two servers running in the same domain: If app is running on Server A and calling content server on Server B, protected with CORS, then necessary SSO cookies aren't passed.

**Expected behavior:**

Expect the cookies to be passed, such that we are seen as being authenticated.

**Steps to reproduce the issue:**

In Chrome:
  - Open page from host A, in Chrome
  - Script attempts to call CS in Tomcat, on host B, but protected by Apache
  - Apache server on host B redirects to SSO host, since it does not have cookies
  - On return Alfresco complains about CORS issue, because it does not recognise SSO host.

**Node version (for build issues):**  

Not a build issue

**New feature request:**

We need to add the withCredentials() call to the super agent request, otherwise we can't make a call if running on a different server:

https://visionmedia.github.io/superagent/#cors

**Comment by ajmas** [comment]
Have made a preliminary change, which manual testing shows to work:

https://github.com/ajmas/alfresco-js-api/tree/issue-357

Haven't made a PR at this point, since there is no testing around this yet

**Comment by eromano** [comment]
Thanks for the contribution
