### ISSUE TITLE
Wrong handling of paths for callCustomApi method.

### ISSUE THREAD

**Issue by jpuerto** [Alfresco/alfresco-js-api#382]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**

A call to "/alfresco/s/slingshot/doclib/action/aspects/node/workspace/SpacesStore/{nodeId}" is resolved always with a slash at the end of the path and results into:
"/alfresco/s/slingshot/doclib/action/aspects/node/workspace/SpacesStore/{nodeId}/"

**Expected behavior:**

The path should not be modified.

**Steps to reproduce the issue:**

Call to method "callCustomApi" with a path not ending in a slash, the result URL contains the slash.

**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
It looks like in 3.0.0 this problem has been already refactored
