### ISSUE TITLE
Make the 'where' parameter for the GET favorites API more flexible

### ISSUE THREAD

**Issue by samuelengelen** [Alfresco/alfresco-js-api#389]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
```

**New feature request:**
The favorites API (GET) allows for a 'where' parameter, but it's limited to an EXISTS with the value file, folder or site. 
The usability of this API would be greatly enhanced if the 'where' parameter was more flexible, like for nodes children, where, for example, it allows filtering on custom node types. In our specific use case this would allow us to move away from our custom API.

**Comment by DenysVuika** [comment]
Is that a request for JavaScript client or platform api?

**Comment by samuelengelen** [comment]
Hmm, right, this is actually a platform api thing. My bad 😅. What would be the best place to make this request?

**Comment by john-knowles** [comment]
Log an ALF project ticket in https://issues.alfresco.com
