### ISSUE TITLE
Legacy renditions api not passing options

### ISSUE THREAD

**Issue by DenysVuika** [Alfresco/alfresco-js-api#400]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**
The method in legacy renditions api does not provide "opts" parameter to the underlying call:
https://github.com/Alfresco/alfresco-js-api/blob/67942c5c0604d80d6c02b3a451a2fcce45b55554/src/api-legacy/content-rest-api/src/api/renditionsApi.ts#L69

**Expected behavior:**

**Steps to reproduce the issue:**

**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
Now seems to be ok
