### ISSUE TITLE
How to get the latest alfresco-js-api.min.js file?

### ISSUE THREAD

**Issue by karamanos** [Alfresco/alfresco-js-api#407]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ ] Bug  
- [x ] Support request
```
**Current behavior:**

I tried to install the browser client API using:
npm install --save @alfresco/js-api
but no dist folder was created in @alfresco/js-api (only src, bundles, _esm*).
How can I get the alfresco-js-api.min.js file?
Many thanks.
**Expected behavior:**

I was expecting to see a dist folder containing the minified JavaScript file.
**Steps to reproduce the issue:**

Execute npm install --save @alfresco/js-api
**Node version (for build issues):**  

v10.14.2
**New feature request:**

**Comment by DenysVuika** [comment]
Please use the issue tracker to raise issues (bugs, feature requests). For generic questions use Gitter or Community Portal.
