### ISSUE TITLE
Parameter renditionType in getRawContent of activiti-api/api/content.api.ts not used

### ISSUE THREAD

**Issue by mfinst** [Alfresco/alfresco-js-api#413]
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**
Parameter renditionType is not used when it passed to getRawContent.
Calling: activiti-app/api/enterprise/content/1/rendition/undefined
leads to a 404 response
**Addition**: Even with the correct renditionType 404 is returned by the RestAPI

**Expected behavior:**
Parameter should be included in pathParams when it exists.
The Rest call should result in a 200 response with the correct file passed to the preview

**Steps to reproduce the issue:**
Call getRawContent with renditionType.
* Have a document involved in a task.
* Click on show of the document inside the TaskDetailsComponent.
* See that one of the Rest calls returns 404 but still an extensionless file can be downloaded.

**Comment by eromano** [comment]
Silver in the next version 3.7.0
