### ISSUE TITLE
Legacy groups API doesn't expose membership methods

### ISSUE THREAD

**Issue by tokewf** [Alfresco/alfresco-js-api#426]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [x] Support request
```
**Current behavior:**
Using the groups API via the `AlfrescoApiService` from `@alfresco/adf-core` in an Angular app like so:
```typescript
import {Component, OnInit} from '@angular/core'
import {AlfrescoApiService} from '@alfresco/adf-core'

@Component({...})
export class FooComponent implements OnInit {
  constructor(private apiService: AlfrescoApiService) { }

  ngOnInit() {
    this.apiService.groupsApi.listGroupMembershipsForPerson('-me-').then(res => console.log(res))
  }
}
```
throws an error that property `listGroupMembershipsForPerson` does not exist on type `GroupsApi`, even though the documentation states that the endpoint is available in Alfresco 5.2.1 and up (https://github.com/Alfresco/alfresco-js-api/blob/development/src/api/content-rest-api/docs/GroupsApi.md#listGroupMembershipsForPerson). I an running Alfresco 6.x, ADF 3.3.0.

Digging through the code, it seems that `AlfrescoApiService.groupsApi` (and the other properties of the service) uses `AlfrescoApiCompatibility` from `@alfresco/js-api`. The legacy`GroupsApi` of this compatibility API is implemented in `src/api-legacy/content-rest-api/src/api/groupsApi.ts`. This maps most—but not all—methods of the _new_ `GroupsApi` in `src/api/content-rest-api/api/groups.api.ts` (Indeed, the new groups API is even made privately available to the legacy groups API as `NewGroupsApi`)

Crucially for my use case, the methods `listGroupMemberships`, `listGroupMembershipsForPerson` and `listGroups` are not available in the legacy groups API, which is the one I have access to via `this.apiService.groupsApi` as in the example above. While I could (rather confusingly) do `this.apiService.groupsApi.groupsApi.listGroupMembershipsForPerson('-me-')`—since the member `groupsApi` of `groupsApi` is the `NewGroupsApi` :confounded:—this new groups API is a private member, so I can't use it.

How do I get access to these API methods in my app?

**Comment by DenysVuika** [comment]
You can use the [GroupsApi](https://github.com/Alfresco/alfresco-js-api/blob/develop/src/api/content-rest-api/api/groups.api.ts#L33) from the newest APIs.

```ts
@Component({...})
export class FooComponent implements OnInit {
  constructor(private apiService: AlfrescoApiService) { }

  ngOnInit() {
    const groupsApi = new GroupsApi(this.apiService.getInstance());
    groupsApi.listGroupMembershipsForPerson('-me-').then(res => console.log(res))
  }
}
```
