### ISSUE TITLE
How to use in browser version 3+

### ISSUE THREAD

**Issue by federicotarantino** [Alfresco/alfresco-js-api#433]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ ] Bug  
- [X] Support request
```
**Current behavior:**
I am trying to use last version (3.5.0) in browser, without success

**Expected behavior:**
Docs to explain how import builded script

**Steps to reproduce the issue:**
- npm run build_all
- no docs

**Comment by fcorti** [comment]
Ciao Federico,

Sorry but this issue is not clear.
What project are you trying to run with this command?

Please raise a question in the hub.alfresco.com or in Discord to have live support.
Feel free to reopen the issue if you can provide info on how to reproduce the problem.

Grazie.
