### ISSUE TITLE
How to get the ticket expiration time?

### ISSUE THREAD

**Issue by THPubs** [Alfresco/alfresco-js-api#545]
Let's say I'm working with multiple Alfresco instances and I don't know the ticket expiration time set in those instances. Now how can I get the expiration time using the JS API?

**Comment by eromano** [comment]
I don't think you can

**Comment by THPubs** [comment]
Any possibility of implementing this feature in the future?

**Comment by eromano** [comment]
Can you tell me more about the problem you are trying to solve?

**Comment by THPubs** [comment]
@eromano I'm trying to store the ticket in my back end so that it never gets exposed in to the front. When storing in the back, I'm trying to set an expiration time for the ticket.

**Comment by DenysVuika** [comment]
@THPubs the expiration settings are configured at the backend side already, in the ACS properties files, no?
