### ISSUE TITLE
IsLoggedIn wrongly report when user is really logged in.

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-js-api#57]
1) Login into demo shell with BPM user and choosing only BPM provider
2) Log out 
3) Login into demo shell with ECM user and choosing only ECM provider
4) Notice the errors in console - NOT EXPECTED
5)Notice that the bpmAuth.isLoggedIn() returns true - NOT EXPECTED

![screen shot 2016-09-22 at 11 26 10](https://cloud.githubusercontent.com/assets/7974125/18744835/7ee0e432-80b7-11e6-8f8b-0af31f9617cb.png)

**Comment by DenisVuyka** [comment]
Notes: `isLoggedIn` just checks the cached ticket after previous logon but not validates it's expiration date.

**Comment by VitoAlbano** [comment]
Actually i've spotted a problem in the code : 

This is the check for isLoggedIn for bpmAuth : 

<img width="402" alt="screen shot 2016-09-22 at 14 08 52" src="https://cloud.githubusercontent.com/assets/7974125/18749309/2e6b6236-80ce-11e6-9f6a-3a3376e4b4cb.png">

this is the value that sometimes gets there : 

![screen shot 2016-09-22 at 14 08 28](https://cloud.githubusercontent.com/assets/7974125/18749319/43755682-80ce-11e6-9fff-104a65b142ac.png)

I need to investigate further to better understand why and when this happens.

**Comment by VitoAlbano** [comment]
This is not a problem of js - api is related to ng2-alfresco-core.
Opened a new issue on the correct repository

https://github.com/Alfresco/alfresco-ng2-components/issues/818
