### ISSUE TITLE
Api to get content url for deleted nodes

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-js-api#58]
It should be possible retrieving content url for deleted nodes. Note that content format differs from the regular nodes, for example: 
`http://localhost:8080/share/proxy/alfresco/api/node/content/archive/SpacesStore/21e5a4ef-c809-4bd4-ae76-c1a805ac29bd/someFile.png?a=true`

**Comment by eromano** [comment]
We can not add this endpoint url because is not inside the new public api. @ohej I think will add a new task in order to support this kind of scenario in the future

**Comment by luguofei123** [comment]
my alfresco vesion is Community - 5.1.0 (r127059-b7),  i can not login in by nodejs. so how can i login in alfresco by nodejs？ follow is my nodejs code :
var AlfrescoApi = require('alfresco-js-api');
this.alfrescoJsApi = new AlfrescoApi();
this.alfrescoJsApi.login('admin', '123456').then(function (data) {
    console.log('API called successfully Login in  BPM and ECM performed ');
}, function (error) {
    console.error(error);
});

**Comment by DenisVuyka** [comment]
@luguofei123 how that relates to the issue?

**Comment by eromano** [comment]
@luguofei123 your question is not related to this topic anyway in order to use the JS-API the minimal supported version is 5.2.

**Comment by luguofei123** [comment]
@eromano  thx.
