### ISSUE TITLE
Library no longer works with ECM

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-js-api#63]
Starting with 0.3.3 library no longer works with standard ECM installation due to errors related to Activiti CSRF code.

**Comment by magemello** [comment]
noe the csrf is sent only for the bpm

**Comment by magemello** [comment]
@DenisVuyka  Can you confirm that the bug is closed?

**Comment by DenisVuyka** [comment]
Works perfect with 0.3.5, closing this bug.
