### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by sanzoghenzo** [Alfresco/alfresco-js-api#649]
Most of the documentation is off: take a look at [createNode](https://github.com/Alfresco/alfresco-js-api/blob/development/src/api/content-rest-api/docs/NodesApi.md#createnode) (or any other method in that page):

- (minor issue) the signature lacks a comma between parameters
- implementation notes are useful for the API explorer, but on the js side we don't have to know about supported content type (JSON and multiform data)
- JSON examples (somewhat useful) are not rendered as code
- The js example is almost useless, with descriptions not commented properly, a wrong signature and no example on how to create the `nodeId` and `nodeBodyCreate` parameters
- the parameters table doesn't render properly, you need to use `<br/>` to get multi line text in a cell.

(It's a bit ironic that a document management system have flaws in the... documentation ;) )

**Comment by DenysVuika** [comment]
@sanzoghenzo most of the JS-API docs are generated by the tool (from the swagger definitions) alongside the client API. 

The whole project is open source, you can help improving the project in a multiple ways: 

- create PR to improve the documentation where you see the fix needed
- create PR to update the swagger definition files (https://github.com/Alfresco/alfresco-js-api/tree/development/definitions)
- create PR to update the code generator (java)

**Comment by sanzoghenzo** [comment]
Hi @DenysVuika ,
thanks for the insight.

I would have helped if I knew where to and what should I edit, but then again, the project lacks in documentation in the contributing part (I don't mean to blame anybody, I too tend to leave the documentation of my -smaller- projects as the last part, if I remember to do it!)

- If I understand correctly, if I directly edit the md files, edits will be lost at the next code generator run, aren't they?
- I think swagger definitions aren't a 1:1 match with the js syntax (there no distinction between query and body parameters, form data and json bodies, etc.), so it's the whole thing that needs a rethought, IMHO.
- Unfortunately I don't know where to start with java, and my employer doesn't expect me to invest time to learn another programming language just to fix "someone else"'s documentation

**Comment by sanzoghenzo** [comment]
BTW, api-legacy folder have better formatted documentation, so maybe it's a kind of regression.

**Comment by fcorti** [comment]
Closing this because too generic.
Feel free to write me to discuss further details or need... also on hoe to contribute to the project.
Thanks.
