### ISSUE TITLE
add a method in order to retrieve the /task-forms/{task-id}/variables

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-js-api#65]
# https://github.com/Alfresco/alfresco-ng2-components/issues/588

**Comment by DenisVuyka** [comment]
Reopened this issue. We need a corresponding enterprise API to be introduced for Process Services and invoked by `alfresco-js-api`

**Comment by tdonovancsra** [comment]
+1 
This is happening to us right now.   Let me know if you need details

**Comment by tdonovancsra** [comment]
Reports is having the same issue as well.  Does this need it's own issue?

**Comment by VitoAlbano** [comment]
Created PR for changing the api rest call. This needs to be checked with ADF to be sure visibility service still works as expected.
@hashraf88 Could you take a look at it?

**Comment by wabson** [comment]
@tdonovancsra yes please raise a separate issue for the reports API

**Comment by VitoAlbano** [comment]
Closing this one to track this enhancement with a new issue.
#199
