### ISSUE TITLE
Provide modular imports -or- avoid index.js concatenation

### ISSUE THREAD

**Issue by sanzoghenzo** [Alfresco/alfresco-js-api#653]
**Type of issue:**
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
```

**Current behavior:**
Building an app that uses this api results in a 415.88KB alfresco module, with a concatenated index js that duplicates the src folder.

![alfrescoBundleSize](https://user-images.githubusercontent.com/977953/77570799-a216ac00-6ecc-11ea-9d90-1cbbcf3ff062.png)

Index.js seems to contain the modules that are not used by my app.

**Expected behavior:**
the packed module contains only the needed code

**Steps to reproduce the issue:**
1. create a new nodejs + webpack project (in my case it's the office yeoman generator)
2. `npm install @alfresco/js-api`
3. import and use some of the api (in my case `AlfrescoApi`, `ContentApi`, `NodesApi`, `SearchApi`)
4. build the project with `webpack -p --mode production`

**New feature request:**
Something like the modular import of lodash would be wonderful.

**Comment by eromano** [comment]
Hi @sanzoghenzo the minified version of the JS-API is under 55 kb

**Comment by DenysVuika** [comment]
We are working on some improvements for tree-shaking
