### ISSUE TITLE
Activiti process status call

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-js-api#67]
In order to be able to show the map below, the following endpoint needs to be added to the activiti javascript API:

http://health2.londonlab.alfresco.me:9999/activiti-app/app/rest/process-instances/374/model-json

<img width="1079" alt="screen shot 2016-10-10 at 16 47 40" src="https://cloud.githubusercontent.com/assets/688226/19242022/4c84da92-8f09-11e6-96f9-fd46c9c7a0f1.png">

**Comment by harigopalakrishna** [comment]
+!

**Comment by eromano** [comment]
I have added two new methods  in order to get these information:

```javascript

var processModelId = 789; // Integer | processModelId
var processModelHistoryId = 789; // Integer | processModelHistoryId

this.alfrescoJsApi.activiti.modelJsonBpmnApi.getEditorDisplayJsonClient(processModelId);
this.alfrescoJsApi.activiti.modelJsonBpmnApi.getHistoricEditorDisplayJsonClient(processModelId, processModelHistoryId);
```
