### ISSUE TITLE
Preserve plural/singular forms for APIs

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-js-api#7]
Naming should correspond to api explorer results (plural and singular forms). For example instead of `this.alfrescoJsApi.node.createFolder` it should be `this.alfrescoJsApi.nodes.createFolder`.

Here's a screenshot for reference:
<img width="523" alt="screen shot 2016-07-09 at 18 34 41" src="https://cloud.githubusercontent.com/assets/503991/16709282/f2982a00-4603-11e6-9688-ad25dedbecab.png">

**Comment by eromano** [comment]
@DenisVuyka good point, thanks Denis
