### ISSUE TITLE
Method overloads not working with JavaScript/Typescript properly

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-js-api#71]
When two or more functions are generated with the same name (aka method overloading) only the last declared function is used, it overwrites previous ones.

Example:

**activiti.taskApi.getRestFieldValues** apis are generated in the following order:
`getRestFieldValues(taskId, field, column)`
`getRestFieldValues(taskId, field)`

At runtime only `getRestFieldValues (taskId, field)` is available.

**Comment by eromano** [comment]
Ok I solved it. Now we have two different calls

```javascript
var taskId = "taskId_example"; // String | taskId

var field = "field_example"; // String | field

var column = "column_example"; // String | column


this.alfrescoJsApi.activiti.taskApi.getRestFieldValuesColumn(taskId, field, column);
this.alfrescoJsApi.activiti.taskApi.getRestFieldValues(taskId, field);

```
