### ISSUE TITLE
Latest version no longer works due to .d.ts errors

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-js-api#78]
Example error when linking with other projects and trying to comple:

`
node_modules/alfresco-js-api/dist/alfresco-js-api.d.ts(1,15): error TS2498: Module '"<path>/ng2-components/ng2-alfresco-core/node_modules/alfresco-js-api/typescript/alfresco-js-api"' uses 'export =' and cannot be used with 'export *'.
`

**Comment by eromano** [comment]
@Denys seems that  the problem is inside the export * that isnside the dist folder that redirect in the typescript folder. I did a fix on this way moving the d.ts file int the root folder and I renamed  it index.d.ts without the redirect and all seems to work fine

**Comment by magemello** [comment]
fixed in 0.3.7
