### ISSUE TITLE
authPath not work

### ISSUE THREAD

**Issue by FuckDoctors** [Alfresco/alfresco-js-api#830]
**Type of issue:**  (check with "[x]")

- [ ] New feature request
- [x] Bug  
- [ ] Support request

**Current behavior:**

I'm using [activiti-modeling-app](https://github.com/Activiti/activiti-modeling-app) and self hosted [activiti-cloud](https://github.com/Activiti/activiti-cloud) with spring security oauth2, not the keycloak.
Following the [activiti-modeling-app](https://github.com/Activiti/activiti-modeling-app) readme and changed the `authPath`, but it always redirected to `${oauth2.host}/protocol/openid-connect/auth`.

After some deep research, I found the path is hard coded here:

https://github.com/Alfresco/alfresco-js-api/blob/develop/src/authentication/oauth2Auth.ts#L122

These urls can be customized by the `app.config.json`?

According to the docs,
https://github.com/Alfresco/alfresco-js-api#password-flow
`authPath` can be changed though, but the `authPath` is not referred in the code.

**Expected behavior:**

These urls can be customized by the `app.config.json`.

**Steps to reproduce the issue:**

**Node version (for build issues):**  

v12.15.0

**New feature request:**

**Comment by DenysVuika** [comment]
@eromano maybe we can integrate suggested changes?

**Comment by DenysVuika** [comment]
should have been addressed already, please reopen if this still happens with the most recent version
