### ISSUE TITLE
Update live search endpoint with latest 5.2 changes

### ISSUE THREAD

**Issue by wabson** [Alfresco/alfresco-js-api#89]
Live search is now 'queries/nodes'

**Comment by montgolfiere** [comment]
Will, thanks for updating.

You might want to also update the main README to refer to Platform 5.2b EA or higher (https://community.alfresco.com/docs/DOC-6366-alfresco-community-edition-201609-ea-release-notes).

In fact, we have now recently release Platform 5.2c EA (ie. Community 201611).

Both of these releases introduce additional incremental API changes, especially as we converge towards the initial GA of Community / Enterprise 5.2.
